const { ipcRenderer } = require('electron');

const api = {
  nativeReady:               () => ipcRenderer.invoke('native:ready'),
  nativeHide:                () => ipcRenderer.invoke('native:hide'),

  nativeClose:               () => ipcRenderer.invoke('native:close'),
  nativeDragMove:            () => ipcRenderer.invoke('native:dragMove'),
  nativeAuthTryRestore:      () => ipcRenderer.invoke('native:authTryRestore'),
  nativeAuthState:           () => ipcRenderer.invoke('native:authState'),
  nativeAuthStart:           () => ipcRenderer.invoke('native:authStart'),
  nativeAuthLogout:          () => ipcRenderer.invoke('native:authLogout'),
  nativeAuthLogin:           (email, password) => ipcRenderer.invoke('native:authLogin', email, password),
  nativeFetchAvatar:         (url) => ipcRenderer.invoke('native:fetchAvatar', url),
  nativeStashCache:          (json) => ipcRenderer.invoke('native:stashCache', json),
  nativeGetAccounts:         () => ipcRenderer.invoke('native:getAccounts'),
  nativeGetSelectedAccount:  () => ipcRenderer.invoke('native:getSelectedAccount'),
  nativeSetSelectedAccount:  (id) => ipcRenderer.invoke('native:setSelectedAccount', id),
  nativeAddAccount:          (name, type) => ipcRenderer.invoke('native:addAccount', name, type),
  nativeRemoveAccount:       (id) => ipcRenderer.invoke('native:removeAccount', id),
  nativeGetVersions:         () => ipcRenderer.invoke('native:getVersions'),
  nativeGetSelectedVersion:  () => ipcRenderer.invoke('native:getSelectedVersion'),
  nativeSetSelectedVersion:  (id) => ipcRenderer.invoke('native:setSelectedVersion', id),
  nativeLaunchStart:         (srv) => ipcRenderer.invoke('native:launchStart', srv),
  nativeLaunchProgress:      () => ipcRenderer.invoke('native:launchProgress'),
  nativeLaunchCancel:        () => ipcRenderer.invoke('native:launchCancel'),
  nativeListMods:            (mc) => ipcRenderer.invoke('native:listMods', mc),
  nativeDownloadMod:         (id, ver) => ipcRenderer.invoke('native:downloadMod', id, ver),
  nativeDeleteMod:           (fn, ver) => ipcRenderer.invoke('native:deleteMod', fn, ver),
  nativeGetSettings:         () => ipcRenderer.invoke('native:getSettings'),
  nativeSetRam:              (mb) => ipcRenderer.invoke('native:setRam', mb),
  nativeGetSystemRam:        () => ipcRenderer.invoke('native:getSystemRam'),
  nativeBrowseFolder:        () => ipcRenderer.invoke('native:browseFolder'),
  nativeSetGameDir:          (dir) => ipcRenderer.invoke('native:setGameDir', dir),
  nativeGetDevConsole:       () => ipcRenderer.invoke('native:getDevConsole'),
  nativeSetDevConsole:       (val) => ipcRenderer.invoke('native:setDevConsole', val),
  nativeGetShowQuickLaunch:  () => ipcRenderer.invoke('native:getShowQuickLaunch'),
  nativeSetShowQuickLaunch:  (val) => ipcRenderer.invoke('native:setShowQuickLaunch', val),
  nativeOpenFolder:          (p) => ipcRenderer.invoke('native:openFolder', p),
  nativeOpenUserMods:        () => ipcRenderer.invoke('native:openUserMods'),
  nativeOpenUrl:             (url) => ipcRenderer.invoke('native:openUrl', url),
  nativeCopyToClipboard:     (text) => ipcRenderer.invoke('native:copyToClipboard', text),
  nativeCheckLauncherUpdate: () => ipcRenderer.invoke('native:checkLauncherUpdate'),
  nativeStartLauncherUpdate: () => ipcRenderer.invoke('native:startLauncherUpdate'),
  nativeUpdateProgress:      () => ipcRenderer.invoke('native:updateProgress'),
  nativeOpenManualUpdate:    () => ipcRenderer.invoke('native:openManualUpdate'),
  nativeStartMicrosoftLogin:   () => ipcRenderer.invoke('native:startMicrosoftLogin'),
  nativeMicrosoftLoginStatus:  () => ipcRenderer.invoke('native:microsoftLoginStatus'),
  nativeCancelMicrosoftLogin:  () => ipcRenderer.invoke('native:cancelMicrosoftLogin'),
  nativeActivateLicense:       (key) => ipcRenderer.invoke('native:activateLicense', key),
};

for (const [key, fn] of Object.entries(api)) {
  window[key] = fn;
}
